import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="theme-color" content="#785ba9"/>
       <link rel="shortcut icon" href="/espoir loém .png" type="image/x-icon" />
       <link rel="apple-touch-icon" href="/espoir loém .png" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased    `}
      >
        {children}
      </body>
    </html>
  );
}
